#!/usr/bin/env python3
"""
Convert pixel art into a sprite for your Tamagotchi.

SETUP (run once):
    pip install Pillow

USAGE:
    python convert_sprite.py my_sprite.png

OUTPUT (two files):
    my_sprite.raw           — raw RGB565 binary
    my_sprite.h             — C header to paste into sprites.h

TIPS:
    - Draw your sprite at any size, it will be scaled to 120×120
    - Use NEAREST scaling so pixel edges stay crisp (not blurry)
    - Transparent pixels are filled with black
    - Export from Piskel: File → Export → PNG → Download
"""

import sys
import argparse
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("Pillow not installed. Run:  pip install Pillow")
    sys.exit(1)


SPRITE_W = 120
SPRITE_H = 120


def convert(input_path: Path, width: int, height: int):
    img = (
        Image.open(input_path)
        .convert("RGBA")
    )

    # Flatten transparency onto black background
    background = Image.new("RGBA", img.size, (0, 0, 0, 255))
    background.paste(img, mask=img.split()[3])
    img = background.convert("RGB")

    # Scale with nearest-neighbour to keep pixel art crisp
    img = img.resize((width, height), Image.Resampling.NEAREST)

    buf = bytearray()
    for r, g, b in img.getdata():
        color = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
        buf.append(color >> 8)
        buf.append(color & 0xFF)

    return buf


def write_raw(buf: bytearray, path: Path):
    path.write_bytes(buf)
    print(f"  {path}  ({len(buf)} bytes, raw RGB565)")


def write_header(buf: bytearray, path: Path, name: str):
    name = name.upper()
    lines = [
        f"// Generated by convert_sprite.py from {path.stem}.png",
        f"// Paste this into sprites.h and add SPRITE_{name} to the Mood switch in Pet.cpp",
        "",
        "#include <pgmspace.h>",
        "",
        f"const uint8_t SPRITE_{name}[] PROGMEM = {{",
    ]
    row = []
    for i, byte in enumerate(buf):
        row.append(f"0x{byte:02X}")
        if len(row) == 16:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    lines += ["};", ""]
    path.write_text("\n".join(lines))
    print(f"  {path}  (SPRITE_{name})")


def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("input", help="PNG file to convert")
    parser.add_argument("--name", "-n", default=None,
                        help="Sprite name (default: filename without extension)")
    parser.add_argument("--width",  "-W", type=int, default=SPRITE_W)
    parser.add_argument("--height", "-H", type=int, default=SPRITE_H)
    args = parser.parse_args()

    input_path = Path(args.input)
    if not input_path.exists():
        print(f"File not found: {input_path}")
        sys.exit(1)

    name = args.name or input_path.stem
    buf  = convert(input_path, args.width, args.height)

    print(f"\nConverting {input_path.name} → {args.width}×{args.height} RGB565\n")
    write_raw(buf,    input_path.with_suffix(".raw"))
    write_header(buf, input_path.with_suffix(".h"), name)
    print(f"\nDone! Paste the contents of {input_path.stem}.h into your sprites.h")


if __name__ == "__main__":
    main()
